#!/usr/bin/env bash

set -ex

[[ "$TRAVIS_BRANCH" != "master" ]] || return

openssl aes-256-cbc -K $encrypted_4ddda811a5fd_key -iv $encrypted_4ddda811a5fd_iv -in id_ecdsa.enc -out id_ecdsa -d
eval "$(ssh-agent -s)"
chmod 600 ./id_ecdsa
ssh-add ./id_ecdsa
yarn run deploy
# vim: ft=sh
